---
title       : Developing Data Products
subtitle    : 
author      : kts
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## The Basics

* The goal is to build a shiny app and slidify documentation
* Both need to be publicly published
* shinyapps.io and ph-pages, here we come!

--- 

## The Application

We chose to keep things simple - use the mtcars data set, predict MPG based on weight, and interact with the user via a text box.

``` {r}
data(mtcars)
model <- lm(mpg~wt, data = mtcars)
print (model)
```

---

## The Results

I'm not one to brag, but this is possibly the world's best fuel economy estimator.  Any time anyone needs to know a rough idea of what the fuel econ of a 1972 vechile, and for whatever reason they happen to know the weight, this should be their go to app.

---

## The Future

As you're well aware, the logical outcome of being able to predict 1972 fuel economies, knowing only the weight, can be but one thing.

World peace.

---

## Thank You

Thanks for reading, and I hope you enjoyed developing data products, and this application in particular.